version: '3'

services:
    dev:
        build: .
        environment:
            - DISPLAY
        hostname: cortez_dev
        volumes:
            - .:/cortez
        ports:
            - "6000:6000"
        network_mode: 'host' # makes x11 windows work for `make run`
        entrypoint: ['make', 'build']


        